Document: mod-cloudflare
Title: Debian mod-cloudflare Manual
Author: <insert document author here>
Abstract: This manual describes what mod-cloudflare is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mod-cloudflare/mod-cloudflare.sgml.gz

Format: postscript
Files: /usr/share/doc/mod-cloudflare/mod-cloudflare.ps.gz

Format: text
Files: /usr/share/doc/mod-cloudflare/mod-cloudflare.text.gz

Format: HTML
Index: /usr/share/doc/mod-cloudflare/html/index.html
Files: /usr/share/doc/mod-cloudflare/html/*.html
