#!/bin/bash
# vim: set ts=2 sw=2 et:
echo "------------------------------------------------"
echo "Activate apache module with 'a2enmod cloudflare'"
echo "------------------------------------------------"
#DEBHELPER#
