#!/bin/bash
# vim: set ts=2 sw=2 et:

install -m 755 /tmp/mod_cloudflare/mod_cloudflare.so /usr/lib/apache2/modules/mod_cloudflare.so
(cd /etc/apache2/mods-enabled && ln -s ../mods-available/cloudflare.conf &&  ln -s ../mods-available/cloudflare.load)


rm -rf /tmp/mod_cloudflare

#DEBHELPER#
